"""HTML Generator for the Composio App Research Pipeline.

Generates the single-file HTML deliverable from all pipeline outputs.
Produces a self-contained HTML page with:
- Dark-mode Tailwind CSS styling (inlined utility classes)
- Interactive filterable data table (category, buildability, auth method filters)
- Executive summary, pattern analysis, verification audit, architecture,
  and transparency sections
- All data embedded as JSON blob with vanilla JavaScript filtering logic
- No external resource requests; functional via file:// protocol
"""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any


class HtmlGenerator:
    """Generates the single-file HTML deliverable from all pipeline outputs.

    The output is a self-contained HTML file with inline CSS (dark-mode),
    embedded data as JSON, and vanilla JavaScript for interactive filtering.
    No external resource requests are made; the file is functional via file:// protocol.
    """

    def generate(self, data: dict[str, Any], output_path: Path) -> None:
        """Generate the self-contained HTML file.

        Assembles all sections (executive summary, data table, pattern analysis,
        verification, architecture, transparency) into a single HTML document
        with inline CSS and embedded JavaScript.

        Args:
            data: Dictionary with keys:
                - "app_records": list of serialized AppRecord dicts
                - "pattern_analysis": serialized PatternAnalysis dict or None
                - "verification_metrics": serialized VerificationMetrics dict or None
                - "intervention_log": list of serialized InterventionEntry dicts
            output_path: Path where the HTML file will be written.
        """
        app_records = data.get("app_records", [])
        pattern_analysis = data.get("pattern_analysis")
        verification_metrics = data.get("verification_metrics")
        intervention_log = data.get("intervention_log", [])

        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Composio App Research Pipeline - Deliverable</title>
{self._embed_tailwind()}
</head>
<body class="bg-gray-900 text-gray-100 min-h-screen">
    <div class="max-w-7xl mx-auto px-4 py-8">
        <header class="mb-12">
            <h1 class="text-4xl font-bold text-white mb-2">Composio App Research: 100 Apps × 10 Categories</h1>
            <p class="text-gray-400 text-lg">Automated agent research pipeline analyzing API buildability for Composio's AI tooling platform</p>
            <p class="text-gray-500 text-sm mt-2">Case study: findings, patterns, agent process, and verification — all in one page</p>
        </header>

        <nav class="mb-8 flex flex-wrap gap-3">
            <a href="#patterns" class="nav-link">Patterns &amp; Insights</a>
            <a href="#data-table" class="nav-link">Research Data (100 apps)</a>
            <a href="#agent" class="nav-link">The Agent</a>
            <a href="#verification" class="nav-link">Verification &amp; Accuracy</a>
            <a href="#transparency" class="nav-link">Transparency</a>
        </nav>

{self._render_patterns_headline(app_records, pattern_analysis)}

{self._render_executive_summary(app_records, pattern_analysis, verification_metrics)}

{self._render_data_table(app_records)}

{self._render_agent_section(app_records, intervention_log)}

{self._render_verification_section(verification_metrics)}

{self._render_transparency_section(app_records, intervention_log)}

{self._render_coverage_summary(app_records)}

        <footer class="mt-12 pt-6 border-t border-gray-700 text-center text-gray-500 text-sm">
            <p>Generated by Composio App Research Pipeline | Built with Composio SDK + Apify + Gemini</p>
        </footer>
    </div>

{self._embed_javascript(app_records)}
</body>
</html>"""

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html_content, encoding="utf-8")

    def _render_executive_summary(
        self,
        app_records: list[dict[str, Any]],
        pattern_analysis: dict[str, Any] | None,
        verification_metrics: dict[str, Any] | None,
    ) -> str:
        """Generate 300-500 word executive summary section.

        Dynamically computes summary statistics from the data including:
        - Total apps researched and success rate
        - Key patterns (dominant auth, easy-win count)
        - Top blockers
        - Recommendations

        Args:
            app_records: List of serialized AppRecord dicts.
            pattern_analysis: Serialized PatternAnalysis dict or None.
            verification_metrics: Serialized VerificationMetrics dict or None.

        Returns:
            HTML string for the executive summary section.
        """
        total_apps = len(app_records)
        complete_count = sum(1 for r in app_records if r.get("research_status") == "complete")
        partial_count = sum(1 for r in app_records if r.get("research_status") == "partial")
        failed_count = sum(1 for r in app_records if r.get("research_status") in ("failed", "unresearchable"))
        success_rate = round((complete_count + partial_count) / max(total_apps, 1) * 100, 1)

        # Count by verdicts
        ready_count = sum(1 for r in app_records if r.get("buildability_verdict") == "ready")
        feasible_count = sum(1 for r in app_records if r.get("buildability_verdict") == "feasible")
        blocked_count = sum(1 for r in app_records if r.get("buildability_verdict") == "blocked")

        # Categories covered
        categories = set(r.get("category", "") for r in app_records)
        category_count = len(categories)

        # Easy-win apps
        easy_win_count = 0
        if pattern_analysis and "easy_win_apps" in pattern_analysis:
            easy_win_count = len(pattern_analysis["easy_win_apps"])

        # Top auth method
        dominant_auth = "N/A"
        if pattern_analysis and "auth_distribution" in pattern_analysis:
            overall = pattern_analysis["auth_distribution"].get("overall", {})
            if overall:
                dominant_auth = max(overall, key=lambda k: overall[k])

        # Top blocker
        top_blocker = "N/A"
        if pattern_analysis and pattern_analysis.get("blocker_rankings"):
            top_blocker = pattern_analysis["blocker_rankings"][0].get("blocker", "N/A")

        # Verification accuracy
        accuracy_text = "not available"
        if verification_metrics and verification_metrics.get("overall_accuracy") is not None:
            accuracy_text = f"{verification_metrics['overall_accuracy']:.1f}%"

        # Self-serve count
        self_serve_count = sum(1 for r in app_records if r.get("access_model") == "self_serve")

        summary_text = (
            f"This report presents the findings of an automated research pipeline that analyzed "
            f"{total_apps} apps across {category_count} categories for potential integration into "
            f"Composio's AI tooling platform. The pipeline assessed each app's authentication methods, "
            f"API surface, access model, and buildability as an agent toolkit. "
            f"Of the {total_apps} apps analyzed, {complete_count} were fully researched, "
            f"{partial_count} were partially researched, and {failed_count} could not be "
            f"researched due to access restrictions or other limitations, yielding an overall "
            f"success rate of {success_rate}%. "
            f"The buildability assessment found {ready_count} apps ready for immediate toolkit "
            f"integration, {feasible_count} apps feasible with some limitations, and "
            f"{blocked_count} apps blocked by critical barriers. "
            f"Among the key patterns identified, {dominant_auth.replace('_', ' ')} emerged as "
            f"the dominant authentication method across the ecosystem. "
            f"{self_serve_count} apps offer self-serve API access, making them accessible "
            f"without partnership agreements. "
            f"The analysis identified {easy_win_count} easy-win apps that combine self-serve access, "
            f"documented public APIs, and a ready buildability verdict, representing the highest-priority "
            f"integration targets. "
            f"The most common barrier to integration is {top_blocker.replace('_', ' ')}, which "
            f"should be addressed through targeted solutions to unblock the largest number of apps. "
            f"Data accuracy was validated through a multi-pass verification loop achieving "
            f"{accuracy_text} overall accuracy. "
            f"Strategic recommendations include: prioritize easy-win apps for rapid catalog expansion, "
            f"invest in connector infrastructure for {dominant_auth.replace('_', ' ')} authentication, "
            f"develop partnership programs for gated-access categories, and address "
            f"{top_blocker.replace('_', ' ')} barriers through dedicated engineering efforts. "
            f"The following sections provide detailed breakdowns of all findings, interactive "
            f"filtering of the full app database, cross-category pattern analysis, "
            f"verification audit results, and full transparency on pipeline limitations."
        )

        return f"""        <section id="executive-summary" class="mb-12">
            <h2 class="section-heading">Executive Summary</h2>
            <div class="card">
                <div class="grid grid-cols-1 md-grid-cols-4 gap-4 mb-6">
                    <div class="stat-card">
                        <div class="stat-value">{total_apps}</div>
                        <div class="stat-label">Apps Analyzed</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">{success_rate}%</div>
                        <div class="stat-label">Success Rate</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">{easy_win_count}</div>
                        <div class="stat-label">Easy Wins</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">{ready_count}</div>
                        <div class="stat-label">Ready to Build</div>
                    </div>
                </div>
                <p class="text-gray-300 leading-relaxed">{html.escape(summary_text)}</p>
            </div>
        </section>"""

    def _render_data_table(self, app_records: list[dict[str, Any]]) -> str:
        """Generate the interactive 100-app filterable table.

        Columns: App Name, Category, Buildability Verdict, Access Model,
        Auth Method(s), Description.

        Verdict badges: green for READY, yellow for FEASIBLE, red for BLOCKED.
        Access badges: blue for self_serve, orange for gated.

        Args:
            app_records: List of serialized AppRecord dicts.

        Returns:
            HTML string for the data table section with filter controls.
        """
        # Collect unique values for filter dropdowns
        categories = sorted(set(r.get("category", "") for r in app_records))
        verdicts = sorted(set(r.get("buildability_verdict", "") for r in app_records))
        auth_methods: set[str] = set()
        for r in app_records:
            for method in r.get("auth_methods", []):
                auth_methods.add(method)
        auth_methods_sorted = sorted(auth_methods)

        # Build category options
        cat_options = "\n".join(
            f'                        <option value="{html.escape(c)}">{html.escape(c)}</option>'
            for c in categories
        )

        # Build verdict options
        verdict_options = "\n".join(
            f'                        <option value="{html.escape(v)}">{html.escape(v)}</option>'
            for v in verdicts
        )

        # Build auth method options
        auth_options = "\n".join(
            f'                        <option value="{html.escape(a)}">{html.escape(a)}</option>'
            for a in auth_methods_sorted
        )

        # Build table rows
        rows = []
        for record in app_records:
            app_name = html.escape(record.get("app_name", ""))
            category = html.escape(record.get("category", ""))
            verdict = record.get("buildability_verdict", "")
            access = record.get("access_model", "")
            auth_list = record.get("auth_methods", [])
            description = html.escape(record.get("description", "")[:120])

            verdict_badge = self._verdict_badge(verdict)
            access_badge = self._access_badge(access)
            auth_display = ", ".join(html.escape(a) for a in auth_list) if auth_list else "N/A"

            rows.append(
                f'                        <tr class="table-row" '
                f'data-category="{html.escape(record.get("category", ""))}" '
                f'data-verdict="{html.escape(verdict)}" '
                f'data-auth="{html.escape(",".join(auth_list))}">'
                f"<td class=\"table-cell font-medium\">{app_name}</td>"
                f'<td class="table-cell">{category}</td>'
                f'<td class="table-cell">{verdict_badge}</td>'
                f'<td class="table-cell">{access_badge}</td>'
                f'<td class="table-cell">{auth_display}</td>'
                f'<td class="table-cell text-gray-400">{description}</td>'
                f'<td class="table-cell">{self._evidence_link(record)}</td>'
                f"</tr>"
            )

        rows_html = "\n".join(rows)

        return f"""        <section id="data-table" class="mb-12">
            <h2 class="section-heading">App Research Data</h2>
            <div class="card">
                <div class="flex flex-wrap gap-4 mb-4 items-end">
                    <div>
                        <label class="filter-label" for="filter-category">Category</label>
                        <select id="filter-category" class="filter-select">
                            <option value="">All Categories</option>
{cat_options}
                        </select>
                    </div>
                    <div>
                        <label class="filter-label" for="filter-verdict">Buildability</label>
                        <select id="filter-verdict" class="filter-select">
                            <option value="">All Verdicts</option>
{verdict_options}
                        </select>
                    </div>
                    <div>
                        <label class="filter-label" for="filter-auth">Auth Method</label>
                        <select id="filter-auth" class="filter-select">
                            <option value="">All Auth Methods</option>
{auth_options}
                        </select>
                    </div>
                    <button id="clear-filters" class="clear-btn">Clear All</button>
                    <span id="row-count" class="text-gray-400 text-sm ml-auto">Showing {len(app_records)} of {len(app_records)} apps</span>
                </div>
                <div id="no-results" class="hidden text-center py-8 text-gray-500">
                    No apps match the current filters. <span id="no-results-count">0 results</span>.
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b border-gray-700">
                                <th class="table-header">App Name</th>
                                <th class="table-header">Category</th>
                                <th class="table-header">Buildability</th>
                                <th class="table-header">Access</th>
                                <th class="table-header">Auth</th>
                                <th class="table-header">Description</th>
                                <th class="table-header">Evidence</th>
                            </tr>
                        </thead>
                        <tbody id="app-table-body">
{rows_html}
                        </tbody>
                    </table>
                </div>
            </div>
        </section>"""

    def _render_pattern_section(self, pattern_analysis: dict[str, Any] | None) -> str:
        """Render pattern analysis with distributions and blocker rankings.

        Shows auth distribution, access distribution, and blocker rankings
        as labeled counts/percentages.

        Args:
            pattern_analysis: Serialized PatternAnalysis dict or None.

        Returns:
            HTML string for the pattern analysis section.
        """
        if pattern_analysis is None:
            return """        <section id="pattern-analysis" class="mb-12">
            <h2 class="section-heading">Pattern Analysis</h2>
            <div class="card">
                <p class="text-gray-400">Pattern analysis data is not available.</p>
            </div>
        </section>"""

        # Auth distribution
        auth_dist = pattern_analysis.get("auth_distribution", {})
        overall_auth = auth_dist.get("overall", {})
        total_auth = sum(overall_auth.values()) if overall_auth else 0

        auth_rows = ""
        for method, count in sorted(overall_auth.items(), key=lambda x: x[1], reverse=True):
            pct = round(count / max(total_auth, 1) * 100, 1)
            bar_width = round(pct)
            auth_rows += (
                f'<div class="dist-row">'
                f'<span class="dist-label">{html.escape(method)}</span>'
                f'<div class="dist-bar-container">'
                f'<div class="dist-bar bg-blue-500" style="width: {bar_width}%"></div>'
                f"</div>"
                f'<span class="dist-value">{count} ({pct}%)</span>'
                f"</div>\n"
            )

        # Access distribution
        access_dist = pattern_analysis.get("access_distribution", {})
        per_category_access = access_dist.get("per_category", {})
        category_classification = access_dist.get("category_classification", {})

        access_rows = ""
        for cat in sorted(per_category_access.keys()):
            counts = per_category_access[cat]
            self_serve = counts.get("self_serve", 0)
            gated = counts.get("gated", 0)
            total = self_serve + gated
            classification = category_classification.get(cat, "")
            badge_class = "badge-blue" if classification == "majority_self_serve" else "badge-orange"
            access_rows += (
                f'<tr class="table-row">'
                f'<td class="table-cell">{html.escape(cat)}</td>'
                f'<td class="table-cell">{self_serve}</td>'
                f'<td class="table-cell">{gated}</td>'
                f'<td class="table-cell"><span class="{badge_class}">{html.escape(classification.replace("_", " "))}</span></td>'
                f"</tr>\n"
            )

        # Blocker rankings
        blocker_rankings = pattern_analysis.get("blocker_rankings", [])
        blocker_rows = ""
        for blocker in blocker_rankings:
            blocker_name = blocker.get("blocker", "")
            count = blocker.get("count", 0)
            rank = blocker.get("rank", 0)
            blocker_rows += (
                f'<tr class="table-row">'
                f'<td class="table-cell">{rank}</td>'
                f'<td class="table-cell">{html.escape(blocker_name.replace("_", " "))}</td>'
                f'<td class="table-cell">{count}</td>'
                f"</tr>\n"
            )

        # Observations
        observations = pattern_analysis.get("observations", [])
        obs_html = ""
        for obs in observations:
            obs_html += (
                f'<div class="observation-card">'
                f'<h4 class="font-semibold text-white mb-1">{html.escape(obs.get("title", ""))}</h4>'
                f'<p class="text-gray-300 text-sm mb-2">{html.escape(obs.get("description", ""))}</p>'
                f'<p class="text-xs text-gray-500">Data: {html.escape(obs.get("supporting_data", ""))}</p>'
                f'<p class="text-xs text-green-400 mt-1">Opportunity: {html.escape(obs.get("opportunity", ""))}</p>'
                f"</div>\n"
            )

        # Easy-win and outreach lists
        easy_wins = pattern_analysis.get("easy_win_apps", [])
        outreach = pattern_analysis.get("outreach_required_apps", [])

        return f"""        <section id="pattern-analysis" class="mb-12">
            <h2 class="section-heading">Pattern Analysis</h2>

            <div class="card mb-6">
                <h3 class="subsection-heading">Authentication Distribution</h3>
                <div class="dist-container">
{auth_rows}
                </div>
            </div>

            <div class="card mb-6">
                <h3 class="subsection-heading">Access Model Distribution</h3>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b border-gray-700">
                                <th class="table-header">Category</th>
                                <th class="table-header">Self-Serve</th>
                                <th class="table-header">Gated</th>
                                <th class="table-header">Classification</th>
                            </tr>
                        </thead>
                        <tbody>
{access_rows}
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="card mb-6">
                <h3 class="subsection-heading">Blocker Rankings</h3>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b border-gray-700">
                                <th class="table-header">Rank</th>
                                <th class="table-header">Blocker</th>
                                <th class="table-header">Count</th>
                            </tr>
                        </thead>
                        <tbody>
{blocker_rows}
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="card mb-6">
                <h3 class="subsection-heading">Key Observations</h3>
                <div class="grid grid-cols-1 md-grid-cols-2 gap-4">
{obs_html}
                </div>
            </div>

            <div class="card">
                <h3 class="subsection-heading">App Classification</h3>
                <div class="grid grid-cols-1 md-grid-cols-2 gap-4">
                    <div>
                        <h4 class="text-green-400 font-semibold mb-2">Easy Wins ({len(easy_wins)})</h4>
                        <ul class="list-disc list-inside text-gray-300 text-sm space-y-1">
                            {"".join(f"<li>{html.escape(app)}</li>" for app in easy_wins[:20])}
                            {"<li class='text-gray-500'>... and " + str(len(easy_wins) - 20) + " more</li>" if len(easy_wins) > 20 else ""}
                        </ul>
                    </div>
                    <div>
                        <h4 class="text-orange-400 font-semibold mb-2">Requires Outreach ({len(outreach)})</h4>
                        <ul class="list-disc list-inside text-gray-300 text-sm space-y-1">
                            {"".join(f"<li>{html.escape(app)}</li>" for app in outreach[:20])}
                            {"<li class='text-gray-500'>... and " + str(len(outreach) - 20) + " more</li>" if len(outreach) > 20 else ""}
                        </ul>
                    </div>
                </div>
            </div>
        </section>"""

    def _render_verification_section(self, verification_metrics: dict[str, Any] | None) -> str:
        """Render verification audit results.

        Shows per-pass accuracy and corrections applied, with visual indicators
        of improvement or regression between passes.

        Args:
            verification_metrics: Serialized VerificationMetrics dict or None.

        Returns:
            HTML string for the verification section.
        """
        if verification_metrics is None:
            return """        <section id="verification" class="mb-12">
            <h2 class="section-heading">Verification &amp; Audit</h2>
            <div class="card">
                <p class="text-gray-400">Verification data is not available.</p>
            </div>
        </section>"""

        passes_completed = verification_metrics.get("passes_completed", 0)
        overall_accuracy = verification_metrics.get("overall_accuracy", 0)
        requires_review = verification_metrics.get("requires_manual_review", False)
        per_pass = verification_metrics.get("per_pass_metrics", [])
        discrepancy_log = verification_metrics.get("discrepancy_log", [])

        # Per-pass table
        pass_rows = ""
        for p in per_pass:
            pass_num = p.get("pass_number", "?")
            accuracy = p.get("accuracy_percentage", 0)
            total_pts = p.get("total_data_points", 0)
            confirmed = p.get("confirmed_points", 0)
            discrepancies = p.get("discrepancies_found", 0)
            corrections = p.get("corrections_applied", 0)

            accuracy_color = "text-green-400" if accuracy >= 80 else "text-yellow-400" if accuracy >= 60 else "text-red-400"

            pass_rows += (
                f'<tr class="table-row">'
                f'<td class="table-cell">Pass {pass_num}</td>'
                f'<td class="table-cell {accuracy_color} font-semibold">{accuracy:.1f}%</td>'
                f'<td class="table-cell">{total_pts}</td>'
                f'<td class="table-cell">{confirmed}</td>'
                f'<td class="table-cell">{discrepancies}</td>'
                f'<td class="table-cell">{corrections}</td>'
                f"</tr>\n"
            )

        # If passes are missing, show indication
        if not per_pass:
            pass_rows = (
                '<tr class="table-row"><td class="table-cell" colspan="6">'
                "No pass data available</td></tr>\n"
            )

        # Review flag
        review_badge = ""
        if requires_review:
            review_badge = '<span class="badge-red ml-2">Manual Review Required</span>'
        else:
            review_badge = '<span class="badge-green ml-2">Passed</span>'

        # Discrepancy summary
        disc_html = ""
        if discrepancy_log:
            disc_rows = ""
            for d in discrepancy_log[:20]:
                disc_rows += (
                    f'<tr class="table-row">'
                    f'<td class="table-cell">{html.escape(d.get("app_name", ""))}</td>'
                    f'<td class="table-cell">{html.escape(d.get("field_name", ""))}</td>'
                    f'<td class="table-cell text-red-300">{html.escape(str(d.get("original_value", "")))}</td>'
                    f'<td class="table-cell text-green-300">{html.escape(str(d.get("corrected_value", "N/A")))}</td>'
                    f'<td class="table-cell">{html.escape(d.get("resolution_status", ""))}</td>'
                    f"</tr>\n"
                )
            disc_html = f"""
            <div class="card mt-6">
                <h3 class="subsection-heading">Discrepancy Log ({len(discrepancy_log)} entries)</h3>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b border-gray-700">
                                <th class="table-header">App</th>
                                <th class="table-header">Field</th>
                                <th class="table-header">Original</th>
                                <th class="table-header">Corrected</th>
                                <th class="table-header">Status</th>
                            </tr>
                        </thead>
                        <tbody>
{disc_rows}
                        </tbody>
                    </table>
                </div>
                {"<p class='text-gray-500 text-sm mt-2'>Showing first 20 of " + str(len(discrepancy_log)) + " entries</p>" if len(discrepancy_log) > 20 else ""}
            </div>"""

        return f"""        <section id="verification" class="mb-12">
            <h2 class="section-heading">Verification &amp; Audit</h2>
            <div class="card">
                <div class="flex items-center mb-4">
                    <span class="text-gray-300">Overall Accuracy: <strong class="text-white">{overall_accuracy:.1f}%</strong></span>
                    {review_badge}
                    <span class="text-gray-500 text-sm ml-4">({passes_completed} passes completed)</span>
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b border-gray-700">
                                <th class="table-header">Pass</th>
                                <th class="table-header">Accuracy</th>
                                <th class="table-header">Total Points</th>
                                <th class="table-header">Confirmed</th>
                                <th class="table-header">Discrepancies</th>
                                <th class="table-header">Corrections</th>
                            </tr>
                        </thead>
                        <tbody>
{pass_rows}
                        </tbody>
                    </table>
                </div>
            </div>
{disc_html}
        </section>"""


    def _render_patterns_headline(self, app_records: list[dict[str, Any]], pattern_analysis: dict[str, Any] | None) -> str:
        """Render the patterns & insights section at the TOP of the page.
        
        This is the headline section - what a reviewer reads first in 2 minutes.
        Shows key patterns, not raw data.
        """
        total = len(app_records)
        if not pattern_analysis:
            return """        <section id="patterns" class="mb-12">
            <h2 class="section-heading">Patterns &amp; Key Insights</h2>
            <div class="card"><p class="text-gray-400">Pattern analysis pending pipeline completion.</p></div>
        </section>"""

        # Compute headline stats
        ready_count = sum(1 for r in app_records if r.get("buildability_verdict") == "ready")
        feasible_count = sum(1 for r in app_records if r.get("buildability_verdict") == "feasible")
        blocked_count = sum(1 for r in app_records if r.get("buildability_verdict") == "blocked")
        self_serve_count = sum(1 for r in app_records if r.get("access_model") == "self_serve")
        gated_count = total - self_serve_count

        # Auth dominance
        overall_auth = pattern_analysis.get("auth_distribution", {}).get("overall", {})
        dominant_auth = max(overall_auth, key=lambda k: overall_auth[k]) if overall_auth else "N/A"
        dominant_auth_pct = round(overall_auth.get(dominant_auth, 0) / max(sum(overall_auth.values()), 1) * 100) if overall_auth else 0

        # Top blocker
        blockers = pattern_analysis.get("blocker_rankings", [])
        top_blocker = blockers[0]["blocker"].replace("_", " ") if blockers else "none"
        top_blocker_count = blockers[0]["count"] if blockers else 0

        # Easy wins
        easy_wins = pattern_analysis.get("easy_win_apps", [])
        outreach = pattern_analysis.get("outreach_required_apps", [])

        # Category breakdown for self-serve
        access_dist = pattern_analysis.get("access_distribution", {})
        cat_class = access_dist.get("category_classification", {})
        self_serve_cats = [c for c, v in cat_class.items() if v == "majority_self_serve"]
        gated_cats = [c for c, v in cat_class.items() if v == "majority_gated"]

        return f"""        <section id="patterns" class="mb-12">
            <h2 class="section-heading">Patterns &amp; Key Insights</h2>
            <p class="text-gray-400 mb-6">Headlines from analyzing {total} apps across 10 categories. Insight over raw table.</p>

            <div class="grid grid-cols-1 md-grid-cols-2 gap-4 mb-6">
                <div class="card" style="border-left: 4px solid #4ade80;">
                    <h3 class="text-green-400 font-bold text-lg mb-2">\U0001f3af Easy Wins: {len(easy_wins)} apps ready today</h3>
                    <p class="text-gray-300 text-sm">{len(easy_wins)} of {total} apps have self-serve access, documented public APIs, and are immediately buildable as agent toolkits. No outreach needed.</p>
                </div>
                <div class="card" style="border-left: 4px solid #f87171;">
                    <h3 class="text-red-400 font-bold text-lg mb-2">\U0001f6a7 Top Blocker: {html.escape(top_blocker)}</h3>
                    <p class="text-gray-300 text-sm">{top_blocker_count} apps blocked by "{html.escape(top_blocker)}" \u2014 the single biggest barrier to expanding the toolkit catalog.</p>
                </div>
                <div class="card" style="border-left: 4px solid #60a5fa;">
                    <h3 class="text-blue-400 font-bold text-lg mb-2">\U0001f511 Auth: {html.escape(dominant_auth)} dominates ({dominant_auth_pct}%)</h3>
                    <p class="text-gray-300 text-sm">{html.escape(dominant_auth)} is the most common auth method. Prioritizing {html.escape(dominant_auth)} connector infrastructure maximizes compatibility.</p>
                </div>
                <div class="card" style="border-left: 4px solid #fb923c;">
                    <h3 class="text-orange-400 font-bold text-lg mb-2">\U0001f512 Access: {self_serve_count} self-serve vs {gated_count} gated</h3>
                    <p class="text-gray-300 text-sm">{len(self_serve_cats)} categories are majority self-serve, {len(gated_cats)} are majority gated. Gated categories need partnership programs.</p>
                </div>
            </div>

            <div class="card mb-6">
                <h3 class="subsection-heading">Buildability Breakdown</h3>
                <div class="flex gap-2 items-center mb-3">
                    <div style="width: {ready_count}%; background: #22c55e; height: 2rem; border-radius: 4px 0 0 4px;" class="flex items-center justify-center text-xs font-bold text-white">{ready_count} ready</div>
                    <div style="width: {feasible_count}%; background: #eab308; height: 2rem;" class="flex items-center justify-center text-xs font-bold text-white">{feasible_count} feasible</div>
                    <div style="width: {blocked_count}%; background: #ef4444; height: 2rem; border-radius: 0 4px 4px 0;" class="flex items-center justify-center text-xs font-bold text-white">{blocked_count} blocked</div>
                </div>
                <p class="text-gray-400 text-sm"><strong class="text-white">{ready_count}%</strong> of apps can become agent toolkits today. <strong class="text-white">{feasible_count}%</strong> are feasible with effort. <strong class="text-white">{blocked_count}%</strong> have critical barriers.</p>
            </div>

            <div class="card">
                <h3 class="subsection-heading">Category Patterns: Self-Serve vs Gated</h3>
                <div class="grid grid-cols-1 md-grid-cols-2 gap-4">
                    <div>
                        <h4 class="text-green-400 font-semibold mb-2">Majority Self-Serve ({len(self_serve_cats)})</h4>
                        <ul class="list-disc list-inside text-gray-300 text-sm space-y-1">
                            {"".join(f"<li>{html.escape(c)}</li>" for c in self_serve_cats)}
                        </ul>
                        <p class="text-gray-500 text-xs mt-2">Developers can get API keys themselves \u2014 fastest integration path.</p>
                    </div>
                    <div>
                        <h4 class="text-orange-400 font-semibold mb-2">Majority Gated ({len(gated_cats)})</h4>
                        <ul class="list-disc list-inside text-gray-300 text-sm space-y-1">
                            {"".join(f"<li>{html.escape(c)}</li>" for c in gated_cats)}
                        </ul>
                        <p class="text-gray-500 text-xs mt-2">Require paid plans, partnerships, or contact-sales \u2014 need outreach strategy.</p>
                    </div>
                </div>
            </div>
        </section>"""

    def _render_agent_section(self, app_records: list[dict[str, Any]], intervention_log: list[dict[str, Any]]) -> str:
        """Render the Agent section: what was built, how it works, where human was needed."""
        total = len(app_records)
        failed = sum(1 for r in app_records if r.get("research_status") in ("failed", "unresearchable"))
        human_needed = len(intervention_log)

        return f"""        <section id="agent" class="mb-12">
            <h2 class="section-heading">The Agent: How This Was Built</h2>
            <div class="card mb-6">
                <p class="text-gray-300 leading-relaxed mb-4">This research was conducted by an automated pipeline built with <strong class="text-white">Composio SDK</strong>, <strong class="text-white">Apify</strong> (web scraping), and <strong class="text-white">Google Gemini</strong> (LLM analysis). The pipeline processes all 100 apps autonomously with human-in-the-loop verification.</p>

                <div class="arch-container">
                    <div class="arch-stage">
                        <div class="arch-number">1</div>
                        <div class="arch-content">
                            <h4 class="font-semibold text-white">Scraper (Composio + Apify RAG Browser)</h4>
                            <p class="text-gray-400 text-sm">Fetches each app's API documentation as markdown. Uses Apify's RAG Web Browser actor via Composio SDK. Tries developer docs URLs, then falls back to search queries.</p>
                            <p class="text-xs text-blue-400 mt-1">Built with: composio.tools.execute("APIFY_RUN_ACTOR_SYNC_GET_DATASET_ITEMS")</p>
                        </div>
                    </div>
                    <div class="arch-stage">
                        <div class="arch-number">2</div>
                        <div class="arch-content">
                            <h4 class="font-semibold text-white">Analyzer (Google Gemini 2.5 Flash)</h4>
                            <p class="text-gray-400 text-sm">Sends scraped markdown to Gemini with a structured extraction prompt. Returns JSON with auth methods, API surface, access model, buildability verdict, and evidence.</p>
                            <p class="text-xs text-blue-400 mt-1">Model: gemini-2.5-flash | Structured JSON output | Conservative defaults for unknowns</p>
                        </div>
                    </div>
                    <div class="arch-stage">
                        <div class="arch-number">3</div>
                        <div class="arch-content">
                            <h4 class="font-semibold text-white">Verifier (Multi-pass evidence checking)</h4>
                            <p class="text-gray-400 text-sm">Re-scrapes evidence URLs and cross-checks each data point. Runs 2\u20134 passes until accuracy \u226580%. Logs discrepancies and applies corrections.</p>
                            <p class="text-xs text-blue-400 mt-1">Accuracy threshold: 80% | Max passes: 4 | Auto-correction on discrepancy</p>
                        </div>
                    </div>
                    <div class="arch-stage">
                        <div class="arch-number">4</div>
                        <div class="arch-content">
                            <h4 class="font-semibold text-white">Pattern Analyzer + HTML Generator</h4>
                            <p class="text-gray-400 text-sm">Pure computation: distributions, blocker rankings, easy-win classification. Then generates this self-contained HTML deliverable with all data embedded inline.</p>
                            <p class="text-xs text-blue-400 mt-1">No external requests in output | Works offline via file:// | Dark-mode, filterable</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card">
                <h3 class="subsection-heading">Where a Human Was Needed</h3>
                <div class="grid grid-cols-1 md-grid-cols-4 gap-4 mb-4">
                    <div class="stat-card">
                        <div class="stat-value">{total}</div>
                        <div class="stat-label">Apps Attempted</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">{total - failed}</div>
                        <div class="stat-label">Auto-Researched</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">{failed}</div>
                        <div class="stat-label">Failed / Needed Human</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">{human_needed}</div>
                        <div class="stat-label">Intervention Points</div>
                    </div>
                </div>
                <ul class="list-disc list-inside text-gray-400 text-sm space-y-2">
                    <li><strong class="text-gray-200">Documentation behind auth walls:</strong> Some apps require login to view developer docs. Agent flags these for manual research.</li>
                    <li><strong class="text-gray-200">Rate limits / Apify quota:</strong> Free-tier Apify has memory limits. Batch processing needs pacing or a paid plan.</li>
                    <li><strong class="text-gray-200">Ambiguous verdicts:</strong> When LLM confidence is low (e.g., docs mention API but no endpoints found), human cross-checks the verdict.</li>
                    <li><strong class="text-gray-200">MCP support verification:</strong> MCP listings aren't always in public docs. Manual check against Composio's catalog needed.</li>
                </ul>
            </div>
        </section>"""


    def _render_architecture_section(self) -> str:
        """Render pipeline architecture documentation.

        Lists pipeline stages in execution order with input/output relationships.

        Returns:
            HTML string for the architecture section.
        """
        stages = [
            {
                "name": "Researcher Agent",
                "description": "Researches individual apps using Composio SDK tools for web search and scraping.",
                "input": "App list (100 apps, 10 per category)",
                "output": "app_records.json",
            },
            {
                "name": "Verifier Agent",
                "description": "Runs multi-pass verification over collected data, checking evidence URLs.",
                "input": "app_records.json",
                "output": "verified_records.json + verification_metrics.json",
            },
            {
                "name": "Pattern Analyzer",
                "description": "Pure computation analyzing verified records for cross-app patterns.",
                "input": "verified_records.json",
                "output": "pattern_analysis.json",
            },
            {
                "name": "HTML Generator",
                "description": "Generates the single-file HTML deliverable from all pipeline outputs.",
                "input": "All JSON outputs + intervention_log.json",
                "output": "deliverable.html",
            },
        ]

        stage_rows = ""
        for i, stage in enumerate(stages, 1):
            stage_rows += (
                f'<div class="arch-stage">'
                f'<div class="arch-number">{i}</div>'
                f'<div class="arch-content">'
                f'<h4 class="font-semibold text-white">{html.escape(stage["name"])}</h4>'
                f'<p class="text-gray-400 text-sm">{html.escape(stage["description"])}</p>'
                f'<div class="flex gap-4 mt-2 text-xs">'
                f'<span class="text-blue-400">Input: {html.escape(stage["input"])}</span>'
                f'<span class="text-green-400">Output: {html.escape(stage["output"])}</span>'
                f"</div>"
                f"</div>"
                f"</div>\n"
            )

        return f"""        <section id="architecture" class="mb-12">
            <h2 class="section-heading">Pipeline Architecture</h2>
            <div class="card">
                <p class="text-gray-400 mb-4">The research pipeline executes four stages sequentially, with each stage producing JSON output consumed by the next:</p>
                <div class="arch-container">
{stage_rows}
                </div>
            </div>
        </section>"""

    def _render_transparency_section(
        self, app_records: list[dict[str, Any]], intervention_log: list[dict[str, Any]]
    ) -> str:
        """Render transparency section.

        Lists:
        (a) Apps that failed research with their failure category
        (b) Apps where data could not be independently confirmed
        (c) Pipeline-level limitations
        (d) Human intervention points

        Args:
            app_records: List of serialized AppRecord dicts.
            intervention_log: List of serialized InterventionEntry dicts.

        Returns:
            HTML string for the transparency section.
        """
        # Failed apps
        failed_apps = [r for r in app_records if r.get("research_status") in ("failed", "unresearchable")]
        failed_rows = ""
        for app in failed_apps:
            failed_rows += (
                f'<tr class="table-row">'
                f'<td class="table-cell">{html.escape(app.get("app_name", ""))}</td>'
                f'<td class="table-cell">{html.escape(app.get("category", ""))}</td>'
                f'<td class="table-cell">{html.escape(app.get("failure_category", "N/A") or "N/A")}</td>'
                f'<td class="table-cell text-gray-400">{html.escape(app.get("failure_reason", "N/A") or "N/A")}</td>'
                f"</tr>\n"
            )

        if not failed_rows:
            failed_rows = '<tr class="table-row"><td class="table-cell" colspan="4">No failures recorded</td></tr>\n'

        # Unconfirmed data points (apps with missing fields)
        unconfirmed_apps = [r for r in app_records if r.get("missing_fields")]
        unconfirmed_rows = ""
        for app in unconfirmed_apps[:20]:
            missing = ", ".join(app.get("missing_fields", []))
            unconfirmed_rows += (
                f'<tr class="table-row">'
                f'<td class="table-cell">{html.escape(app.get("app_name", ""))}</td>'
                f'<td class="table-cell text-gray-400">{html.escape(missing)}</td>'
                f"</tr>\n"
            )

        if not unconfirmed_rows:
            unconfirmed_rows = '<tr class="table-row"><td class="table-cell" colspan="2">All data points confirmed</td></tr>\n'

        # Intervention log
        intervention_rows = ""
        for entry in intervention_log:
            intervention_rows += (
                f'<tr class="table-row">'
                f'<td class="table-cell">{html.escape(entry.get("app_name", ""))}</td>'
                f'<td class="table-cell">{html.escape(entry.get("pipeline_stage", ""))}</td>'
                f'<td class="table-cell text-gray-400">{html.escape(entry.get("reason", ""))}</td>'
                f'<td class="table-cell text-gray-500">{html.escape(entry.get("timestamp", ""))}</td>'
                f"</tr>\n"
            )

        if not intervention_rows:
            intervention_rows = '<tr class="table-row"><td class="table-cell" colspan="4">No human interventions required</td></tr>\n'

        return f"""        <section id="transparency" class="mb-12">
            <h2 class="section-heading">Transparency &amp; Limitations</h2>

            <div class="card mb-6">
                <h3 class="subsection-heading">Failed Research ({len(failed_apps)} apps)</h3>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b border-gray-700">
                                <th class="table-header">App Name</th>
                                <th class="table-header">Category</th>
                                <th class="table-header">Failure Category</th>
                                <th class="table-header">Reason</th>
                            </tr>
                        </thead>
                        <tbody>
{failed_rows}
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="card mb-6">
                <h3 class="subsection-heading">Unconfirmed Data Points</h3>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b border-gray-700">
                                <th class="table-header">App Name</th>
                                <th class="table-header">Missing Fields</th>
                            </tr>
                        </thead>
                        <tbody>
{unconfirmed_rows}
                        </tbody>
                    </table>
                </div>
                {"<p class='text-gray-500 text-sm mt-2'>Showing first 20 of " + str(len(unconfirmed_apps)) + " apps with missing data</p>" if len(unconfirmed_apps) > 20 else ""}
            </div>

            <div class="card mb-6">
                <h3 class="subsection-heading">Human Intervention Log</h3>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b border-gray-700">
                                <th class="table-header">App</th>
                                <th class="table-header">Stage</th>
                                <th class="table-header">Reason</th>
                                <th class="table-header">Timestamp</th>
                            </tr>
                        </thead>
                        <tbody>
{intervention_rows}
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="card">
                <h3 class="subsection-heading">Pipeline Limitations</h3>
                <ul class="list-disc list-inside text-gray-400 text-sm space-y-2">
                    <li>Research relies on publicly available documentation; apps requiring authenticated access for developer docs may have incomplete data.</li>
                    <li>MCP support detection is limited to publicly announced integrations; internal or beta MCP servers are not discoverable.</li>
                    <li>API coverage assessment (full/partial/minimal) is based on documentation review and may not reflect undocumented endpoints.</li>
                    <li>Rate limit information is often not publicly documented and may be understated in the assessment.</li>
                    <li>Buildability verdicts represent a point-in-time assessment; apps may update their API offerings after research.</li>
                </ul>
            </div>
        </section>"""

    def _render_coverage_summary(self, app_records: list[dict[str, Any]]) -> str:
        """Render coverage summary showing per-category breakdown.

        Args:
            app_records: List of serialized AppRecord dicts.

        Returns:
            HTML string for the coverage summary section.
        """
        from composio_research.config import CATEGORIES

        # Count per-category
        category_counts: dict[str, dict[str, int]] = {}
        for cat in CATEGORIES:
            category_counts[cat] = {"total": 0, "success": 0}

        for record in app_records:
            cat = record.get("category", "")
            if cat in category_counts:
                category_counts[cat]["total"] += 1
                status = record.get("research_status", "")
                if status in ("complete", "partial"):
                    category_counts[cat]["success"] += 1

        total = len(app_records)
        total_success = sum(c["success"] for c in category_counts.values())

        coverage_rows = ""
        for cat in CATEGORIES:
            counts = category_counts[cat]
            pct = round(counts["success"] / max(counts["total"], 1) * 100)
            bar_class = "bg-green-500" if pct >= 80 else "bg-yellow-500" if pct >= 50 else "bg-red-500"
            coverage_rows += (
                f'<tr class="table-row">'
                f'<td class="table-cell">{html.escape(cat)}</td>'
                f'<td class="table-cell">{counts["success"]}/{counts["total"]}</td>'
                f'<td class="table-cell">'
                f'<div class="dist-bar-container inline-block w-24">'
                f'<div class="{bar_class} dist-bar" style="width: {pct}%"></div>'
                f"</div>"
                f" {pct}%"
                f"</td>"
                f"</tr>\n"
            )

        # Unresearchable apps
        unresearchable = [r for r in app_records if r.get("research_status") == "unresearchable"]
        unresearchable_html = ""
        if unresearchable:
            items = "".join(
                f'<li>{html.escape(r.get("app_name", ""))} ({html.escape(r.get("category", ""))}): '
                f'{html.escape(r.get("failure_reason", "Unknown reason") or "Unknown reason")}</li>'
                for r in unresearchable
            )
            unresearchable_html = f"""
                <h4 class="text-gray-300 font-semibold mt-4 mb-2">Unresearchable Apps</h4>
                <ul class="list-disc list-inside text-gray-400 text-sm space-y-1">
                    {items}
                </ul>"""

        return f"""        <section id="coverage" class="mb-12">
            <h2 class="section-heading">Coverage Summary</h2>
            <div class="card">
                <div class="flex gap-6 mb-4">
                    <span class="text-gray-300">Total Apps: <strong class="text-white">{total}</strong></span>
                    <span class="text-gray-300">Successfully Researched: <strong class="text-green-400">{total_success}</strong></span>
                    <span class="text-gray-300">Target: <strong class="text-white">100</strong></span>
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b border-gray-700">
                                <th class="table-header">Category</th>
                                <th class="table-header">Researched / Target</th>
                                <th class="table-header">Coverage</th>
                            </tr>
                        </thead>
                        <tbody>
{coverage_rows}
                        </tbody>
                    </table>
                </div>
{unresearchable_html}
            </div>
        </section>"""

    def _embed_tailwind(self) -> str:
        """Return inline CSS that provides dark-mode utility styling.

        Instead of the Tailwind CDN (which would require an external request),
        this embeds a minimal set of utility classes covering all styles used
        in the HTML output. This ensures the file works offline via file:// protocol.

        Returns:
            HTML <style> block with all required CSS classes.
        """
        return """    <style>
        /* Reset and base */
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; }

        /* Colors */
        .bg-gray-900 { background-color: #111827; }
        .bg-gray-800 { background-color: #1f2937; }
        .bg-gray-700 { background-color: #374151; }
        .text-gray-100 { color: #f3f4f6; }
        .text-gray-200 { color: #e5e7eb; }
        .text-gray-300 { color: #d1d5db; }
        .text-gray-400 { color: #9ca3af; }
        .text-gray-500 { color: #6b7280; }
        .text-white { color: #ffffff; }
        .text-green-400 { color: #4ade80; }
        .text-green-500 { color: #22c55e; }
        .text-yellow-400 { color: #facc15; }
        .text-yellow-500 { color: #eab308; }
        .text-red-400 { color: #f87171; }
        .text-red-500 { color: #ef4444; }
        .text-blue-400 { color: #60a5fa; }
        .text-blue-500 { color: #3b82f6; }
        .text-orange-400 { color: #fb923c; }
        .bg-green-500 { background-color: #22c55e; }
        .bg-green-900 { background-color: #14532d; }
        .bg-yellow-500 { background-color: #eab308; }
        .bg-yellow-900 { background-color: #713f12; }
        .bg-red-500 { background-color: #ef4444; }
        .bg-red-900 { background-color: #7f1d1d; }
        .bg-blue-500 { background-color: #3b82f6; }
        .bg-blue-900 { background-color: #1e3a5f; }
        .bg-orange-900 { background-color: #7c2d12; }

        /* Layout */
        .min-h-screen { min-height: 100vh; }
        .max-w-7xl { max-width: 80rem; }
        .mx-auto { margin-left: auto; margin-right: auto; }
        .px-4 { padding-left: 1rem; padding-right: 1rem; }
        .py-8 { padding-top: 2rem; padding-bottom: 2rem; }
        .p-4 { padding: 1rem; }
        .p-6 { padding: 1.5rem; }
        .mb-2 { margin-bottom: 0.5rem; }
        .mb-4 { margin-bottom: 1rem; }
        .mb-6 { margin-bottom: 1.5rem; }
        .mb-8 { margin-bottom: 2rem; }
        .mb-12 { margin-bottom: 3rem; }
        .mt-1 { margin-top: 0.25rem; }
        .mt-2 { margin-top: 0.5rem; }
        .mt-4 { margin-top: 1rem; }
        .mt-12 { margin-top: 3rem; }
        .ml-2 { margin-left: 0.5rem; }
        .ml-4 { margin-left: 1rem; }
        .ml-auto { margin-left: auto; }
        .mr-2 { margin-right: 0.5rem; }
        .pt-6 { padding-top: 1.5rem; }
        .mb-1 { margin-bottom: 0.25rem; }

        /* Flexbox */
        .flex { display: flex; }
        .flex-wrap { flex-wrap: wrap; }
        .items-center { align-items: center; }
        .items-end { align-items: flex-end; }
        .gap-3 { gap: 0.75rem; }
        .gap-4 { gap: 1rem; }
        .gap-6 { gap: 1.5rem; }

        /* Grid */
        .grid { display: grid; }
        .grid-cols-1 { grid-template-columns: repeat(1, minmax(0, 1fr)); }
        @media (min-width: 768px) {
            .md-grid-cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }
            .md-grid-cols-4 { grid-template-columns: repeat(4, minmax(0, 1fr)); }
        }

        /* Typography */
        .text-4xl { font-size: 2.25rem; line-height: 2.5rem; }
        .text-2xl { font-size: 1.5rem; line-height: 2rem; }
        .text-xl { font-size: 1.25rem; line-height: 1.75rem; }
        .text-lg { font-size: 1.125rem; line-height: 1.75rem; }
        .text-sm { font-size: 0.875rem; line-height: 1.25rem; }
        .text-xs { font-size: 0.75rem; line-height: 1rem; }
        .font-bold { font-weight: 700; }
        .font-semibold { font-weight: 600; }
        .font-medium { font-weight: 500; }
        .text-center { text-align: center; }
        .leading-relaxed { line-height: 1.75; }
        .list-disc { list-style-type: disc; }
        .list-inside { list-style-position: inside; }
        .space-y-1 > * + * { margin-top: 0.25rem; }
        .space-y-2 > * + * { margin-top: 0.5rem; }
        .inline-block { display: inline-block; }

        /* Width */
        .w-full { width: 100%; }
        .w-24 { width: 6rem; }

        /* Border */
        .border-t { border-top-width: 1px; border-top-style: solid; }
        .border-b { border-bottom-width: 1px; border-bottom-style: solid; }
        .border-gray-700 { border-color: #374151; }
        .rounded { border-radius: 0.25rem; }
        .rounded-lg { border-radius: 0.5rem; }
        .rounded-full { border-radius: 9999px; }

        /* Overflow */
        .overflow-x-auto { overflow-x: auto; }
        .hidden { display: none; }

        /* Custom components */
        .card {
            background-color: #1f2937;
            border-radius: 0.5rem;
            padding: 1.5rem;
            border: 1px solid #374151;
        }
        .section-heading {
            font-size: 1.5rem;
            font-weight: 700;
            color: #ffffff;
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 2px solid #374151;
        }
        .subsection-heading {
            font-size: 1.125rem;
            font-weight: 600;
            color: #e5e7eb;
            margin-bottom: 0.75rem;
        }
        .stat-card {
            background-color: #374151;
            border-radius: 0.5rem;
            padding: 1rem;
            text-align: center;
        }
        .stat-value {
            font-size: 1.5rem;
            font-weight: 700;
            color: #ffffff;
        }
        .stat-label {
            font-size: 0.75rem;
            color: #9ca3af;
            margin-top: 0.25rem;
        }
        .nav-link {
            color: #60a5fa;
            text-decoration: none;
            padding: 0.25rem 0.75rem;
            border-radius: 0.25rem;
            font-size: 0.875rem;
            transition: background-color 0.2s;
        }
        .nav-link:hover {
            background-color: #374151;
        }

        /* Filter controls */
        .filter-label {
            display: block;
            font-size: 0.75rem;
            color: #9ca3af;
            margin-bottom: 0.25rem;
        }
        .filter-select {
            background-color: #374151;
            color: #f3f4f6;
            border: 1px solid #4b5563;
            border-radius: 0.375rem;
            padding: 0.5rem 0.75rem;
            font-size: 0.875rem;
            min-width: 10rem;
        }
        .filter-select:focus {
            outline: none;
            border-color: #60a5fa;
            box-shadow: 0 0 0 2px rgba(96, 165, 250, 0.2);
        }
        .clear-btn {
            background-color: #4b5563;
            color: #f3f4f6;
            border: none;
            border-radius: 0.375rem;
            padding: 0.5rem 1rem;
            font-size: 0.875rem;
            cursor: pointer;
            transition: background-color 0.2s;
        }
        .clear-btn:hover {
            background-color: #6b7280;
        }

        /* Table */
        .table-header {
            text-align: left;
            padding: 0.75rem;
            color: #9ca3af;
            font-weight: 600;
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }
        .table-row {
            border-bottom: 1px solid #1f2937;
        }
        .table-row:hover {
            background-color: #374151;
        }
        .table-cell {
            padding: 0.75rem;
            color: #d1d5db;
        }

        /* Badges */
        .badge-green {
            display: inline-block;
            padding: 0.125rem 0.5rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: 600;
            background-color: #14532d;
            color: #4ade80;
        }
        .badge-yellow {
            display: inline-block;
            padding: 0.125rem 0.5rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: 600;
            background-color: #713f12;
            color: #facc15;
        }
        .badge-red {
            display: inline-block;
            padding: 0.125rem 0.5rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: 600;
            background-color: #7f1d1d;
            color: #f87171;
        }
        .badge-blue {
            display: inline-block;
            padding: 0.125rem 0.5rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: 600;
            background-color: #1e3a5f;
            color: #60a5fa;
        }
        .badge-orange {
            display: inline-block;
            padding: 0.125rem 0.5rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: 600;
            background-color: #7c2d12;
            color: #fb923c;
        }

        /* Distribution bars */
        .dist-container {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }
        .dist-row {
            display: flex;
            align-items: center;
            gap: 0.75rem;
        }
        .dist-label {
            min-width: 7rem;
            font-size: 0.875rem;
            color: #d1d5db;
        }
        .dist-bar-container {
            flex: 1;
            height: 1.25rem;
            background-color: #374151;
            border-radius: 0.25rem;
            overflow: hidden;
        }
        .dist-bar {
            height: 100%;
            border-radius: 0.25rem;
            transition: width 0.3s;
        }
        .dist-value {
            min-width: 6rem;
            text-align: right;
            font-size: 0.75rem;
            color: #9ca3af;
        }

        /* Architecture */
        .arch-container {
            display: flex;
            flex-direction: column;
            gap: 1rem;
        }
        .arch-stage {
            display: flex;
            align-items: flex-start;
            gap: 1rem;
            padding: 1rem;
            background-color: #374151;
            border-radius: 0.5rem;
            border-left: 3px solid #60a5fa;
        }
        .arch-number {
            min-width: 2rem;
            height: 2rem;
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: #1e3a5f;
            color: #60a5fa;
            border-radius: 9999px;
            font-weight: 700;
            font-size: 0.875rem;
        }
        .arch-content {
            flex: 1;
        }

        /* Observation cards */
        .observation-card {
            background-color: #374151;
            border-radius: 0.5rem;
            padding: 1rem;
            border-left: 3px solid #4ade80;
        }
    </style>"""

    def _embed_javascript(self, app_records: list[dict[str, Any]]) -> str:
        """Return inline JavaScript with embedded app data and filtering logic.

        Embeds the full app records as a JSON blob and implements:
        - Category filter dropdown
        - Buildability filter dropdown
        - Auth method filter dropdown
        - AND logic for multi-filter combinations
        - Clear-all button
        - "No results" message when no apps match
        - Row count update on filter change

        Args:
            app_records: List of serialized AppRecord dicts.

        Returns:
            HTML <script> block with embedded data and filter logic.
        """
        # Serialize app data for embedding
        json_data = json.dumps(app_records, ensure_ascii=False, separators=(",", ":"))

        return f"""    <script>
    (function() {{
        'use strict';

        const APP_DATA = {json_data};
        const totalApps = APP_DATA.length;

        const filterCategory = document.getElementById('filter-category');
        const filterVerdict = document.getElementById('filter-verdict');
        const filterAuth = document.getElementById('filter-auth');
        const clearBtn = document.getElementById('clear-filters');
        const rowCount = document.getElementById('row-count');
        const noResults = document.getElementById('no-results');
        const noResultsCount = document.getElementById('no-results-count');
        const tableBody = document.getElementById('app-table-body');

        function applyFilters() {{
            const categoryVal = filterCategory ? filterCategory.value : '';
            const verdictVal = filterVerdict ? filterVerdict.value : '';
            const authVal = filterAuth ? filterAuth.value : '';

            const rows = tableBody ? tableBody.querySelectorAll('tr') : [];
            let visibleCount = 0;

            rows.forEach(function(row) {{
                const rowCategory = row.getAttribute('data-category') || '';
                const rowVerdict = row.getAttribute('data-verdict') || '';
                const rowAuth = row.getAttribute('data-auth') || '';

                let show = true;

                if (categoryVal && rowCategory !== categoryVal) {{
                    show = false;
                }}
                if (verdictVal && rowVerdict !== verdictVal) {{
                    show = false;
                }}
                if (authVal) {{
                    const authMethods = rowAuth.split(',');
                    if (authMethods.indexOf(authVal) === -1) {{
                        show = false;
                    }}
                }}

                row.style.display = show ? '' : 'none';
                if (show) visibleCount++;
            }});

            if (rowCount) {{
                rowCount.textContent = 'Showing ' + visibleCount + ' of ' + totalApps + ' apps';
            }}
            if (noResults) {{
                if (visibleCount === 0) {{
                    noResults.classList.remove('hidden');
                    if (noResultsCount) {{
                        noResultsCount.textContent = '0 results';
                    }}
                }} else {{
                    noResults.classList.add('hidden');
                }}
            }}
        }}

        function clearFilters() {{
            if (filterCategory) filterCategory.value = '';
            if (filterVerdict) filterVerdict.value = '';
            if (filterAuth) filterAuth.value = '';
            applyFilters();
        }}

        if (filterCategory) filterCategory.addEventListener('change', applyFilters);
        if (filterVerdict) filterVerdict.addEventListener('change', applyFilters);
        if (filterAuth) filterAuth.addEventListener('change', applyFilters);
        if (clearBtn) clearBtn.addEventListener('click', clearFilters);
    }})();
    </script>"""

    # ========================================================================
    # Private helpers
    # ========================================================================

    def _verdict_badge(self, verdict: str) -> str:
        """Return an HTML badge for a buildability verdict.

        Args:
            verdict: One of "ready", "feasible", "blocked".

        Returns:
            HTML span with appropriate badge class.
        """
        badge_map = {
            "ready": ("badge-green", "Ready"),
            "feasible": ("badge-yellow", "Feasible"),
            "blocked": ("badge-red", "Blocked"),
        }
        css_class, label = badge_map.get(verdict, ("badge-yellow", verdict.title()))
        return f'<span class="{css_class}">{html.escape(label)}</span>'

    def _access_badge(self, access: str) -> str:
        """Return an HTML badge for an access model.

        Args:
            access: One of "self_serve", "gated".

        Returns:
            HTML span with appropriate badge class.
        """
        badge_map = {
            "self_serve": ("badge-blue", "Self-Serve"),
            "gated": ("badge-orange", "Gated"),
        }
        css_class, label = badge_map.get(access, ("badge-orange", access.replace("_", " ").title()))
        return f'<span class="{css_class}">{html.escape(label)}</span>'

    def _evidence_link(self, record: dict[str, Any]) -> str:
        """Return an HTML link to the evidence URL if available."""
        evidence_urls = record.get("evidence_urls", {})
        url = evidence_urls.get("docs_url", "")
        if url:
            short = url.replace("https://", "").replace("http://", "")[:30]
            return f'<a href="{html.escape(url)}" target="_blank" class="text-blue-400 text-xs hover:underline">{html.escape(short)}...</a>'
        return '<span class="text-gray-600 text-xs">N/A</span>'
